# Tipos de Frequência

### Importando bibliotecas

In [1]:
import pandas as pd
import numpy as np

### Gerando dados

In [2]:
idade = np.array([10,10,10,10,30,30,30,30,30,30,30,30,50,50,50,50,70,70,70,90])
idade

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

In [3]:
idade.dtype

dtype('int32')

### Gerando o vetor de idades de forma diferente 

In [4]:
idade_rep = np.concatenate([np.repeat(10,4), np.repeat(30,8), np.repeat(50,4), np.repeat(70,3), np.repeat(90,1)])
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

##### ou 

In [5]:
idade_rep = np.repeat(np.array([10, 30, 50, 70, 90]), repeats = [4,8,4,3,1], axis=0)
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

### Transformando o array em dataframe 

In [6]:
df = pd.DataFrame(idade, columns=['idades'])

In [7]:
df.head()

idades
0      10
1      10
2      10
3      10
4      30

### Calculando as frequências simples 

##### Usando groupby 

In [8]:
df.groupby('idades').size()

idades
10    4
30    8
50    4
70    3
90    1
dtype: int64

##### Usando value_counts()

In [9]:
df.idades.value_counts().sort_index()

10    4
30    8
50    4
70    3
90    1
Name: idades, dtype: int64

### Calculando a quantidade total de alunos 

In [10]:
df.groupby('idades').size().sum()

20

In [11]:
df2 = pd.DataFrame(df.groupby('idades').size(), columns=['frequência_simples'])
df2

frequência_simples
idades                    
10                       4
30                       8
50                       4
70                       3
90                       1

### Calculando as outras frequências e inserindo no dataframe 

##### Calculando as frequências acumuladas simples usando o método cumsum()

In [12]:
df2['frequência_acumulada'] = df.groupby('idades').size().cumsum()
df2

frequência_simples  frequência_acumulada
idades                                          
10                       4                     4
30                       8                    12
50                       4                    16
70                       3                    19
90                       1                    20

##### Calculando as frequências relativas simples

In [13]:
df2['frequência_relativa_simples'] = df.groupby('idades').size()/df2.frequência_simples.sum()
df2

frequência_simples  frequência_acumulada  frequência_relativa_simples
idades                                                                       
10                       4                     4                         0.20
30                       8                    12                         0.40
50                       4                    16                         0.20
70                       3                    19                         0.15
90                       1                    20                         0.05

##### ou 

In [14]:
df2['frequência_relativa_simples'] = df2.frequência_simples/df2.frequência_simples.sum()
df2

frequência_simples  frequência_acumulada  frequência_relativa_simples
idades                                                                       
10                       4                     4                         0.20
30                       8                    12                         0.40
50                       4                    16                         0.20
70                       3                    19                         0.15
90                       1                    20                         0.05

##### Calculando as frequências relativas acumuladas 

In [15]:
df2['frequência_relativa_acumulada'] = df2.frequência_acumulada/df2.frequência_simples.sum()
df2

frequência_simples  frequência_acumulada  frequência_relativa_simples  \
idades                                                                          
10                       4                     4                         0.20   
30                       8                    12                         0.40   
50                       4                    16                         0.20   
70                       3                    19                         0.15   
90                       1                    20                         0.05   

        frequência_relativa_acumulada  
idades                                 
10                               0.20  
30                               0.60  
50                               0.80  
70                               0.95  
90                               1.00

##### ou 

In [16]:
df2['frequência_relativa_acumulada'] = df2.frequência_relativa_simples.cumsum()
df2

frequência_simples  frequência_acumulada  frequência_relativa_simples  \
idades                                                                          
10                       4                     4                         0.20   
30                       8                    12                         0.40   
50                       4                    16                         0.20   
70                       3                    19                         0.15   
90                       1                    20                         0.05   

        frequência_relativa_acumulada  
idades                                 
10                               0.20  
30                               0.60  
50                               0.80  
70                               0.95  
90                               1.00